### ISSUE TITLE
Exceed Energy doesn't appear when searching in the "Goal" menu

### ISSUE THREAD

**Issue by JaneSmith** [malulleybovo/PSO2AffixingAssistant#24]
**Describe the bug**
When using the "Affixing Goal" menu (after clicking the plus button on the left sidebar), if I search for "Exceed Energy", "Exceed", "Energy", etc. I cannot get the Exceed Energy ability to show up. I don't think this is a case of it being a new affix that hasn't been added yet, as it *does* show up when searching in the "Affixing Formula Sheet" menu.

**To Reproduce**
1. Go to the "Affixing Goal" menu, by clicking the plus button on the left sidebar.
2. Search for "Exceed Energy".
3. The ability does not show up in the search results.

**Expected behavior**
I expected "Exceed Energy" to show up in the list of available affixes.

**Desktop (please complete the following information):**
 - OS: Fedora Silverblue 32
 - Browser: Mozilla Firefox
 - Version: 77.0.1

***

Thank you so much for developing this tool by the way. I was very pleased to see that you're continuing to update it (e.g. adding support for the new transplant system). For me, this tool is enormously more helpful than the other affixing one that people use. Great job!

**Comment by malulleybovo** [comment]
Thank you for reporting this issue as well as for the words of appreciation. "Exceed Energy" is in fact in the Database. The fact that this ability does not show as an option in the menu is due to the Affixing Assistant being unaware of any way to transfer the ability. Any ability that has no way of being transferred at the moment will not show as an option in order not to mislead users. However, you are correct in that it should show since Special Ability Transplants has made it possible to transfer any ability (note that some abilities still may not be transferred through affixing). I will update this issue when this is fixed.

**Comment by malulleybovo** [comment]
This issue has been resolved in v1.1.2 of the Affixing Assistant.
