### ISSUE TITLE
NA version?

### ISSUE THREAD

**Issue by Aida-Enna** [malulleybovo/PSO2AffixingAssistant#30]
**Is your feature request related to a problem? Please describe.**
Nope!

**Describe the solution you'd like**
Is there a NA version planned/in development? If not, I can fork and create one (if that's OK!). Just didn't want to step on any toes or anything :3

**Describe alternatives you've considered**
Deleting the NA version of the game.

**Comment by malulleybovo** [comment]
I've had this in my radar for a little while, just have not found the time to map all the names and make the necessary additions to the language file. If you wish to contribute, you are totally free to do so. Just make sure you are following the guide in [CONTRIBUTING.md](https://github.com/malulleybovo/PSO2AffixingAssistant/blob/master/CONTRIBUTING.md).

Its a relatively simple (but lengthy) change if you check the project structure. You would basically have to include an identifier such as 'naen' in line 51 of viewcontroller.js, and make sure that every item in lang.js has a new field for that identifier. Example of one such change: _{jp:"", en:""} -> {jp:"", en:"", naen:""}_

Note that currently if you press the laguage button in the application it loops through the available languages but it does not give any clue to the users which language it changed to (no alerts or anything). That's ok with only english/japanese since they're distinct enough to recognize... but the distinction between english-JPserver vs english-NAserver is very slight so some sort of clue might be helpful.

In CONTRIBUTING.md I specify that only merge requests related to database update are accepted, but I count something like this as an exception to that (since there are no changes to the inner workings of the assistant). So feel free to come up with solutions to address this.

Side note:
"Deleting the NA version of the game." lol

**Comment by malulleybovo** [comment]
Issue addressed in https://github.com/malulleybovo/PSO2AffixingAssistant/pull/47, which will be reviewed as soon as I've got time for that.

**Comment by malulleybovo** [comment]
Issue has been addressed in v1.3.0 with massive thanks to everyone involved in https://github.com/malulleybovo/PSO2AffixingAssistant/pull/47 for including the translation items for the global version!
