### ISSUE TITLE
Affixing Assistant 1.1.6 ???

### ISSUE THREAD

**Issue by DARKM4GM4** [malulleybovo/PSO2AffixingAssistant#36]
i can't find the 1.1.6 version but only the 1.1.5 one and it doesn't have the new affixes (guardian soul & absolute glare)

how can i update to 1.1.6 ?

**Comment by malulleybovo** [comment]
Hello. It seems like v1.1.6 was not correctly deployed. However, v1.1.6 can be used at https://malulleybovo.github.io/PSO2AffixingAssistant/index.debug.html.
Regarding the new affixes such as guardian soul, they have yet to be added. If you wish to contribute to the next update, I suggest checking out the following pull request: https://github.com/malulleybovo/PSO2AffixingAssistant/pull/34.
With that said, updates from me on this project might take a bit of time since I am struggling to find the time to put here due to personal reasons.
