### ISSUE TITLE
Some receptor combinations can't be selected.

### ISSUE THREAD

**Issue by s1120cbxxxx** [malulleybovo/PSO2AffixingAssistant#4]
Hello

The following combinations can't be selected.

1. Factor Receptor + Soul Receptor
    can't move Factor receptor to Fodder 3
![9663b1b68cb899e6f5b313de801ce612](https://user-images.githubusercontent.com/47063379/51791325-90f8df00-21e4-11e9-8f67-746e640c5cf2.png)

2. Extreceptor + any soul (available at pso2es Emergency)
    can't move Extreceptor to Fodder 5
![7b9667227c4bafed3517d284edc45b57](https://user-images.githubusercontent.com/47063379/51791370-4330a680-21e5-11e9-8e4d-ea3fc0471c06.png)

3. Soul Receptor + any soul (available at pso2es)
    can't move Soul receptor to Fodder 5
![714ba23ef4c7c846f9268bdc9de4f242](https://user-images.githubusercontent.com/47063379/51791344-de754c00-21e4-11e9-8cdb-830391987daf.png)

These combinations are actually available.

Thanks for your work! and I'm sorry, my english is not good ...

**Comment by malulleybovo** [comment]
Thank you for the note! What you pointed out is in fact due to how the assistant was designed. PSO2es EQ bosses are unpredictable, which makes these combinations you pointed out not frequently available in shop. For instance, soul receptor+vol soul exists but it's very possible that at some point you either won't find it available in shop or will find it for an absurdly high price. Therefore, the assistant assumes these combinations of abilities to not exist and disables them. This is to ensure that the assistant always produces viable formulas that can be followed at any time.

I don't plan on changing this assumption since it's correct behavior by design. But I admit the assistant isn't perfect and so, when I have time I'll try to investigate a way to allow users to tweak that (or force it to happen on the review screen) without changing the assistant design.

**As an additional note, Soul Receptor can be added via Special Ability Factor which does enable any combination with Soul Receptor (not just souls). However, it is most commonly used by purchasing PSO2es drops so this has also been disconsidered in the design of the assistant. Nonetheless, this possibility does encourage investigation as well.

**Comment by FireswordMRM** [comment]
Factor receptor dropped always with Soul receptor on units and minimum 3 slots
Factor receptor dropped always with Soul receptor and Gift receptor on weapons and minimum 4 slots
(Possible buy Dominacio weapon with 3s Factor receptor only with soul receptor via Ethernal Tower exchange shop)

Factor receptor can not be dropped without Soul receptor (but possible via Special Ability Factor on Dominacio series)
Gift receptor can not be dropped without Soul receptor

**Comment by malulleybovo** [comment]
Good point about gift and factor receptors. That's something that completely scaped me. I'll see what can be done about that.

**Comment by malulleybovo** [comment]
Good point about gift and factor receptors. That's something that completely escaped me. I'll see what can be done about that.

**Comment by malulleybovo** [comment]
This one turned out a bit more troublesome to fix. A potential fix was added, but I'm leaving it in the debug build only until I'm confident this did not produce side-effects.
You can try out the fix here:
https://malulleybovo.github.io/PSO2AffixingAssistant/index.debug.html

**Comment by FireswordMRM** [comment]
I am found some issue.
![chrome_2019-02-25_00-03-42](https://user-images.githubusercontent.com/47332065/53305340-956ef100-3891-11e9-8163-ec1e9675dfad.png)
After press confirm, fodder 0 always change with fodder with Astral and Ether, not a big issue
![chrome_2019-02-25_00-03-55](https://user-images.githubusercontent.com/47332065/53305341-99027800-3891-11e9-9f52-1a744f0cca3d.png)

Another one
Nothing happens after clicking confirm, work only if remove affixe by upslotting
![chrome_2019-02-25_00-07-52](https://user-images.githubusercontent.com/47332065/53305366-d1a25180-3891-11e9-9326-59e6408c8225.png)
the result should be like [here](http://arks-layer.com/abilitysim/#!/s=TK01.ZA01&1=TK02.SB04&2=TK03.SB05&3=TK04.ZA01&4=TK05.ZA01&5=TK06.ZA01&r=TJ01.VJ03.ZA01&o=A06)

**Comment by malulleybovo** [comment]
@FireswordMRM I have an idea of what is causing all that. However, could you create a new issue, add a title and maybe copy/paste what you said up there? That is all for issue tracking purposes. We will follow up on this issue there, thank you!

If you're new to this, you can open a new issue by going to https://github.com/malulleybovo/PSO2AffixingAssistant/issues/ and clicking on the green "New Issue" button towards the top right portion of the page. Then add a title and description to the issue.

**Comment by malulleybovo** [comment]
After a fair bit of testing and bug spotting, I am now fairly confident the Assistant is treating Receptors how it is intended to. Non-transferable receptors still cannot be put together with "normal" abilities, but a select few combination of receptors can be put together (any combination between Soul Receptor, Gift Receptor, and Factor Receptor).

**Comment by malulleybovo** [comment]
Improvement on Receptor handling has been released. Feel free to reopen the issue if further problems related to this arise.
