### ISSUE TITLE
bug with Non-transferable receptors and "normal" abilities.

### ISSUE THREAD

**Issue by FireswordMRM** [malulleybovo/PSO2AffixingAssistant#7]
Nothing happens after clicking confirm, work only if remove guidance trainer +5%
![chrome_2019-02-25_13-58-47](https://user-images.githubusercontent.com/47332065/53333350-ab6ac900-3906-11e9-86b0-2ec3bcc5b3f8.png)
I think the problem is that the non-transferable receptors is put in main fodder
![chrome_2019-02-25_14-08-03](https://user-images.githubusercontent.com/47332065/53333488-187e5e80-3907-11e9-861b-1a49ebecdc60.png)
Need change script: non-transferable receptors always combine in fodder 5.  Like this
![chrome_2019-02-25_14-17-11](https://user-images.githubusercontent.com/47332065/53333827-1072ee80-3908-11e9-8f73-7ceaaab1da08.png)

We are have now only 2 group of them Soul Receptor, Gift Receptor, and Factor Receptor. 
Another group it is Extreceptor and Soul Receptor but they may appear separately and users can split it manually

**Comment by NextTime000** [comment]
![extreceptorissue](https://user-images.githubusercontent.com/8367971/53367456-3a321280-3914-11e9-9f39-e16f3ae7836f.PNG)
yeah I noticed I can't put anything at all on the same item as extreceptor, when it drops from es with soul receptor and some other abilities often

**Comment by malulleybovo** [comment]
This turned out to be a flaw in the algorithm. A counter-measure has been added to aid that.

Regarding the Extreceptor note, the assistant does not like putting together abilities that may not be available in shop 100% of the time (such as Extreceptor + Vol Soul, which is likely to run out in shops if PSO2ES does not add the Vol EQ for a long time). I am, instead, considering tweak-only exceptions, allowing users to force abilities like Extreceptor to pair up with a select few other abilities.

**Comment by FireswordMRM** [comment]
hmm i am try did test with 3 returner V. All work fine with the exception of separated receptors
![chrome_2019-02-26_17-38-26](https://user-images.githubusercontent.com/47332065/53420822-90bf4f80-39ed-11e9-960c-1224c38de3b3.png)
![chrome_2019-02-26_17-38-33](https://user-images.githubusercontent.com/47332065/53420834-961c9a00-39ed-11e9-8fb5-5d3af5315f56.png)

But with 2  returner V nothing happens after clicking "confirm" if "guidance trainer +5%" selected. As I said at the beginning.

**Comment by malulleybovo** [comment]
This fix is still ongoing and has not been added to the production version of the assistant. If you want to try out latest, pre-release features and fixes, you will need to access the debug build of the assistant instead.

You can do so at: https://malulleybovo.github.io/PSO2AffixingAssistant/index.debug.html
Note that the debug build may contain unfinished features and fixes since it is intended to be a developer test ground.

**Comment by malulleybovo** [comment]
Fixes for Guidance Trainer and Receptor handling have been released. Hopefully this makes the assistant more robust and flexible.
Feel free to reopen the issue if further problems related to these topics arise.
