### ISSUE TITLE
Short url.

### ISSUE THREAD

**Issue by FireswordMRM** [malulleybovo/PSO2AffixingAssistant#9]
Is it possible to add support for short url, as in PSO2 Damage Calculator http://4rt.info/psod/ ?

**Comment by malulleybovo** [comment]
Possible it definitely is. I even investigated this a bit some time ago while looking into bitly URLs. The reason I didn't add that until now is time and uncertainty of how exactly to generate them since I only briefly looked into it. So yes, it is possible and I may add that, but not sure when.

I will keep this issue open for further updates in the future.

**Comment by malulleybovo** [comment]
Support for short link URLs has been added and it is ready for use. Shout out to @Aida-Enna for the contribution.
